version: 2
updates:
    -   package-ecosystem: pip
        directory: /
        schedule:
            interval: weekly
        groups:
            dependencies:
                dependency-type: production
                update-types:
                    - minor
                    - patch
            dev-dependencies:
                dependency-type: development

    -   package-ecosystem: github-actions
        directory: /
        schedule:
            interval: weekly
