repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        # Pre-commit hook version.
        rev: v5.0.0
        hooks:
            -   id: check-yaml
                exclude: mkdocs.yaml
            -   id: check-yaml
                args: [ --unsafe ]
                files: mkdocs.yaml
            -   id: end-of-file-fixer
            -   id: trailing-whitespace
                exclude_types:
                    - markdown

    -   repo: https://github.com/astral-sh/ruff-pre-commit
        # Ruff version.
        rev: v0.11.10
        hooks:
            # Run the linter.
            -   id: ruff-check
                args: [ --fix ]
            # Run the formatter.
            -   id: ruff-format
