services:
    etuutt_bot:
        build: .
        image: ungdev/etuutt-discord-bot
        env_file: .env
        ports:
            - "3000:3000"
        volumes:
            - data:/usr/src/etuutt/data

volumes:
    data:
