name: Docker Build and Push

on:
    push:
        branches:
            - prod

jobs:
    docker:
        runs-on: [self-hosted, Linux, X64]
        steps:
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to SIA Registry
                uses: docker/login-action@v3
                with:
                    registry: ${{ secrets.HARBOR_URL }}
                    username: ${{ secrets.HARBOR_USERNAME }}
                    password: ${{ secrets.HARBOR_TOKEN }}

            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Build and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    tags: |
                        ${{ secrets.HARBOR_URL }}/ung/etuutt-bot:latest,${{ secrets.HARBOR_URL }}/ung/etuutt-bot:${{ github.sha }},${{ secrets.HARBOR_URL }}/ung/etuutt-bot:${{ github.run_number }}
                    platforms: linux/amd64
