name: Deploy docs
on:
    push:
        branches:
            - main
        paths-ignore:
            - .pre-commit-config.yaml
            - requirements.txt
            - requirements-dev.txt
    workflow_dispatch:

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v6
            -   uses: actions/setup-python@v6
                with:
                  python-version-file: ".python-version"
            -   uses: astral-sh/setup-uv@v7
                with:
                    enable-cache: true
            -   run: uv run --group docs mkdocs gh-deploy --force
