name: deploy_docs
on:
    push:
        branches:
            - main
        paths-ignore:
            - .pre-commit-config.yaml
            - requirements.txt
            - requirements-dev.txt
    workflow_dispatch:

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-python@v5
                with:
                    python-version: 3.x
            -   name: Cache virtualenv
                uses: actions/cache@v4
                with:
                    key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version}}-${{ hashFiles('requirements.txt') }}
                    path: .venv
            -   name: Install dependencies
                run: |
                    python -m venv .venv
                    source .venv/bin/activate
                    python -m pip install --upgrade pip
                    python -m pip install -r requirements-dev.txt
                    echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
                    echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
            -   run: mkdocs gh-deploy --force
